# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: Mahendra Shaji Kurian

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Mahendra Shaji Kurian

description: Data Scientist
author:
  name: Mahendra Shaji Kurian
  email: shajimahendra@gmail.com
  github: MahendraShaji
  twitter: 
  pinterest: 
  linkedin: shaji-mahendra
  bio: Data Scientist
  email_md5: 

rss_path: 
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
